### ISSUE TITLE
Submitting DOI returns "Requested endpoint could not be found"

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper-Plugins/mdm-plugin-digital-object-identifiers#9]
**Describe the bug**
Assuming that:

1. A DOI profile has been completed
2. A catalogue item has been finalised, and
3. That catalogue item is public

When submitting the DOI to the DOI system via `POST /api/{domainType}/{id}/doi?submissionType=draft` a `400` response is returned with this response body:

```json
{
    "status": 400,
    "reason": "Bad Request",
    "errorCode": "DOIC01",
    "message": "Requested endpoint could not be found https://api.test.datacite.org/dois/10.80079/2rnz-7938",
    "path": "/api/dataModels/b307ad8b-f47a-4e0b-a182-4c6f4c188a00/doi",
    "devMode": true,
    "version": "4.8.0-SNAPSHOT"
}
```

What is strange though is that the endpoint mentioned in the error message can be accessed via the DataCite API (`GET` request with Basic authorization in the HTTP request headers), so the DOI does exist. Why the plugin does not return a valid Mauro response back though is unknown.

**To Reproduce**
1. Create a Data Model
2. Add a DOI profile to the Data Model while it is in draft state, entering all mandatory values. This is due to an issue with profiles, described in MauroDataMapper/mdm-core#130
3. Save the DOI profile
4. Now finalise the Data Model, then make it public (via the UI is usually the easiest way)
5. Now send `POST /api/dataModels/{id}/doi?submissionType=draft`, where `{id}` is the identifier of the Data Model.

**Expected behavior**
A `200` response should have been returned, with the DOI profile updated automatically to include a status, identifier, and suffix.

**Screenshots**
The image below shows that a DOI profile is included with a catalogue item, and the response that is returned:
![image](https://user-images.githubusercontent.com/3219480/129031855-d71b53bf-cfc1-44e4-b93d-c886709ae272.png)

**Additional context**
This is the stack trace from the log file:

```
2021-08-11 13:41:27,502 [080-exec-8] DEBUG w.c.DigitalObjectIdentifiersServerClient : Client created to connect to https://api.test.datacite.org
2021-08-11 13:41:27,929 [080-exec-8] DEBUG u.a.o.s.m.datamodel.DataModelService     : Saving Simple Test DataModel(b307ad8b-f47a-4e0b-a182-4c6f4c188a00) without batching
2021-08-11 13:41:27,935 [080-exec-8] DEBUG u.a.o.s.m.datamodel.DataModelService     : Saving Simple Test DataModel(b307ad8b-f47a-4e0b-a182-4c6f4c188a00) without batching
2021-08-11 13:41:27,949 [080-exec-8] DEBUG .s.m.p.d.DigitalObjectIdentifiersService : Exporting model using template
2021-08-11 13:41:28,245 [080-exec-8] ERROR o.g.web.errors.GrailsExceptionResolver   : ApiBadRequestException occurred when processing request: [POST] /api/dataModels/b307ad8b-f47a-4e0b-a182-4c6f4c188a00/doi - parameters:
submissionType: draft
Requested endpoint could not be found https://api.test.datacite.org/dois/10.80079/2rnz-7938. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: uk.ac.ox.softeng.maurodatamapper.api.exception.ApiBadRequestException: Requested endpoint could not be found https://api.test.datacite.org/dois/10.80079/2rnz-7938
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at uk.ac.ox.softeng.maurodatamapper.plugins.digitalobjectidentifiers.web.client.DigitalObjectIdentifiersServerClient.makeRequestToClient(DigitalObjectIdentifiersServerClient.groovy:114)
	at uk.ac.ox.softeng.maurodatamapper.plugins.digitalobjectidentifiers.web.client.DigitalObjectIdentifiersServerClient.putMapToClient(DigitalObjectIdentifiersServerClient.groovy:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at uk.ac.ox.softeng.maurodatamapper.plugins.digitalobjectidentifiers.DigitalObjectIdentifiersService.$tt__submitAsDraft(DigitalObjectIdentifiersService.groovy:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at uk.ac.ox.softeng.maurodatamapper.plugins.digitalobjectidentifiers.DigitalObjectIdentifiersService.$tt__submitDoi(DigitalObjectIdentifiersService.groovy:159)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at uk.ac.ox.softeng.maurodatamapper.plugins.digitalobjectidentifiers.DigitalObjectIdentifiersController.$tt__submit(DigitalObjectIdentifiersController.groovy:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	... 15 common frames omitted
```

**Comment by pjmonks** [comment]
Latest changes to `mdm-plugin-profile` now supports `uneditable` profile fields. The DOI profile has now been updated to support this, meaning key fields like `identifier`, `prefix`, `suffix` etc are now read-only.

This certainly solves the issue from a UI perspective, as a user is now unable to submit bad data to profile fields and cannot enter the state described in this issue. But it may still be possible for anyone to submit faulty data directly via the REST endpoint and still encounter this issue.

Although the priority of this issue has reduced significantly, I still think it should be kept open and reviewed to plug this hole in the process.

**Comment by olliefreeman** [comment]
This issue has been entirely mitigated as the uneditable and derived fields CANNOT be submitted and set via the API, any data in them is completely ignored when we map the submitted profile to the clean profile.

This mapping is done specifically to stop extra junk fields being submitted into a profile. We generate a clean profile and then map each field from the submitted profile across to the clean, however ONLY if the field exists and is editable
